package com.mybatis.demo.hsqldb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import org.junit.Test;


/**
 * 
 * 类HsqldbTest.java的实现描述：TODO 类实现描述 
 * @author yuezhihua 2015年7月9日 下午2:35:14
 */
public class HsqldbTest {

	
	
	
	@Test
	public void test() throws Exception{
		 // 加载HSQL DB的JDBC驱动
        Class.forName("org.hsqldb.jdbcDriver");
        // 在内存中建立数据库db,用户名为sa,密码为空
        Connection conn = DriverManager.getConnection("jdbc:hsqldb:mem:db", "sa", "");
        Statement stat = conn.createStatement();
        // 新建数据表
        int count = stat.executeUpdate("create table push(id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,map VARCHAR(5120) )");
        System.out.println("create table result:"+count);
        
        // 插入数据
        String sql = "INSERT INTO push VALUES(1,'map')";
        count = stat.executeUpdate(sql);
        System.out.println("Insert result:"+count);
        // 查询数据
        PreparedStatement pstmt = conn
                .prepareStatement("SELECT * FROM push");
        ResultSet rs = pstmt.executeQuery();
        while (rs.next()) {
            String s = null;
            s = rs.getString(1) + " : " + rs.getString(2);
            System.out.println(s);
        }
        System.out.println("SELECT IS OK!11111");
        
        
	}
	
}
