

drop index user_main if exists;
drop index user_role if exists;
drop index role_main if exists;
drop index permission_main if exists;
drop index role_permission if exists;




CREATE TABLE user_main (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  username varchar(50)  ,
  password varchar(100)  ,
  email varchar(50)  ,
  profile varchar(100)  ,
  locked varchar(10) ,
  sex varchar(10) ,
  create_time TIMESTAMP  ,
  update_time TIMESTAMP  ,
  PRIMARY KEY (id)
) ;



CREATE TABLE user_role (
  user_id int NOT NULL  ,
  role_id int NOT NULL ,
  PRIMARY KEY (user_id,role_id)
);


CREATE TABLE role_main (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  role_name varchar(20) DEFAULT NULL ,
  available varchar(10) DEFAULT 'TRUE' ,
  description varchar(50) DEFAULT NULL ,
  create_time timestamp ,
  update_time timestamp ,
  PRIMARY KEY (id)
) ;


CREATE TABLE permission_main (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  permission_name varchar(20) DEFAULT NULL ,
  description varchar(50) DEFAULT NULL ,
  url varchar(100) DEFAULT NULL ,
  available varchar(10) DEFAULT 'TRUE' ,
  leaf varchar(10) DEFAULT NULL ,
  parent_id int DEFAULT NULL ,
  orders int DEFAULT NULL ,
  create_time timestamp ,
  update_time timestamp ,
  PRIMARY KEY (id)
);


CREATE TABLE role_permission (
  role_id int NOT NULL  ,
  permission_id int NOT NULL ,
  PRIMARY KEY (role_id,permission_id)
);



